from enum import IntEnum


class ObjectType(IntEnum):
    DOUJINSHI = 1
    DOUJIN_CG = 2
    DOUJIN_SOFT = 3
    DOUJIN_OTHER = 4
    MANGA = 5
    MANGA_PARTIAL = 6
    COMMERCIAL_MAGAZINE = 7
    COMMERCIAL_CG = 8
    COMMERCIAL_SOFT = 9
    COMMERCIAL_OTHER = 10
    COMMERCIAL_NOVEL = 11
    COMMERCIAL_ARTBOOK = 12
    COMMERCIAL_OTHER_BOOK = 13
    TELEPHONE_CARD = 14
    SHITAJIKI = 15
    POSTER = 16
    POSTCARD = 17
    CALENDAR = 18
    BOOTLEG = 19
    UNKNOWN = 20
    DOUJIN_NOVEL = 21
    DOUJIN_MUSIC = 22
    DOUJIN_MOVIE = 23
    DOUJIN_GOODS = 24
    COMMERCIAL_MOOK = 25
